from datetime import UTC, datetime

import pytest
from langchain_core.messages import AIMessage
from langchain_core.runnables import RunnableLambda
from langgraph.types import Command

import app.tools.registry as registry_module
from app.graph.builder import build_graph
from app.graph.report import IncidentReport
from app.graph.schemas import (
    ApprovalGateDecision,
    DiagnosticPlan,
    DiagnosticStep,
    IncidentClassification,
)
from app.main import _build_response
from app.rag.retriever import RetrievedChunk
from app.tools.approval import ApprovalDecision
from app.tools.registry import ToolResult, ToolSpec, register_tool


class FakeRetriever:
    def search(self, query: str, top_k: int = 5) -> list[RetrievedChunk]:
        return [
            RetrievedChunk(
                text="x", source_id="cisa-ir-vr-playbooks", title="T", page=1, score=0.9
            )
        ]


def _classify_llm() -> RunnableLambda:
    return RunnableLambda(
        lambda messages: IncidentClassification(
            category="unauthorized_access",
            severity="critical",
            confidence=0.95,
            reasoning="Brute force confirmed with a successful login afterwards",
            missing_info=[],
        )
    )


def _tools_llm() -> RunnableLambda:
    return RunnableLambda(lambda messages: AIMessage(content="", tool_calls=[]))


def _plan_llm() -> RunnableLambda:
    return RunnableLambda(
        lambda messages: DiagnosticPlan(
            steps=[
                DiagnosticStep(
                    description="Review auth logs",
                    rationale="Confirm scope",
                    expected_evidence="Log entries",
                    priority=1,
                )
            ]
        )
    )


def _block_ip_proposal_llm(ip: str = "45.83.65.12") -> RunnableLambda:
    return RunnableLambda(
        lambda messages: ApprovalGateDecision.model_validate(
            {
                "proposed_actions": [
                    {
                        "tool_name": "block_ip",
                        "args": {"ip": ip},
                        "justification": "10 failed logins from this IP, then a success",
                        "risk_note": "Verify the IP isn't a shared NAT gateway",
                    }
                ]
            }
        )
    )


def _no_proposals_llm() -> RunnableLambda:
    return RunnableLambda(lambda messages: ApprovalGateDecision(proposed_actions=[]))


def _report_llm() -> RunnableLambda:
    """None of these tests exercise report generation itself — just enough to let the graph
    reach the final "completed" state without constructing a real ChatGroq."""
    return RunnableLambda(lambda messages: IncidentReport(markdown="# Report\n\nStub report."))


def _build(approval_llm: RunnableLambda) -> object:
    return build_graph(
        classify_llm=_classify_llm(),
        tools_llm=_tools_llm(),
        plan_llm=_plan_llm(),
        approval_llm=approval_llm,
        report_llm=_report_llm(),
        retriever=FakeRetriever(),
    )


def test_empty_proposals_do_not_interrupt() -> None:
    graph = _build(_no_proposals_llm())
    config = {"configurable": {"thread_id": "no-proposals"}}

    result = graph.invoke({"incident_description": "minor phishing click"}, config=config)

    assert "__interrupt__" not in result
    assert result.get("audit_log", []) == []


def test_proposal_interrupts_with_stable_action_id_across_resume() -> None:
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "approve-thread"}}

    first = graph.invoke({"incident_description": "brute force"}, config=config)
    assert "__interrupt__" in first
    proposed = first["__interrupt__"][0].value["proposed_actions"]
    assert len(proposed) == 1
    action_id = proposed[0]["id"]

    # get_state (a fresh read, simulating a GET after a restart) must report the exact same
    # pending action id, not one regenerated by a fresh LLM call
    snapshot = graph.get_state(config)
    assert snapshot.interrupts[0].value["proposed_actions"][0]["id"] == action_id


def test_approved_action_executes_and_is_audited() -> None:
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "approve-thread-2"}}

    first = graph.invoke({"incident_description": "brute force"}, config=config)
    action_id = first["__interrupt__"][0].value["proposed_actions"][0]["id"]

    approval = ApprovalDecision(
        action_id=action_id, approved=True, decided_at=datetime.now(UTC), comment="go ahead"
    )
    resumed = graph.invoke(Command(resume=[approval.model_dump(mode="json")]), config=config)

    assert "__interrupt__" not in resumed
    assert len(resumed["audit_log"]) == 1
    entry = resumed["audit_log"][0]
    assert entry.executed is True
    assert entry.decision.approved is True
    assert "45.83.65.12" in entry.result_summary

    response = _build_response("approve-thread-2", resumed, ())
    assert response.status == "completed"
    assert response.audit_log[0].executed is True


def test_rejected_action_is_not_executed_but_still_audited() -> None:
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "reject-thread"}}

    first = graph.invoke({"incident_description": "brute force"}, config=config)
    action_id = first["__interrupt__"][0].value["proposed_actions"][0]["id"]

    decision = ApprovalDecision(
        action_id=action_id, approved=False, decided_at=datetime.now(UTC), comment="not yet"
    )
    resumed = graph.invoke(Command(resume=[decision.model_dump(mode="json")]), config=config)

    assert "__interrupt__" not in resumed
    entry = resumed["audit_log"][0]
    assert entry.executed is False
    assert entry.decision.approved is False
    assert entry.result_summary == "Rejected by analyst; no action taken."


def test_missing_decision_defaults_to_not_approved() -> None:
    """If the client's approvals list omits an action entirely, it must still be audited
    as not-approved rather than silently dropped or (worse) executed."""
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "missing-decision-thread"}}

    graph.invoke({"incident_description": "brute force"}, config=config)
    resumed = graph.invoke(Command(resume=[]), config=config)

    assert "__interrupt__" not in resumed
    entry = resumed["audit_log"][0]
    assert entry.executed is False
    assert entry.decision.approved is False


def test_proposed_action_carries_a_preview_of_the_real_commands() -> None:
    """block_ip is registered with preview_fn=block_ip itself (see app/tools/firewall.py), so
    the analyst must see the exact commands before deciding — not just the bare IP."""
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "preview-thread"}}

    result = graph.invoke({"incident_description": "brute force"}, config=config)

    preview = result["__interrupt__"][0].value["proposed_actions"][0]["preview"]
    assert preview is not None
    assert preview["findings"][0]["ufw_command"] == "ufw deny from 45.83.65.12 to any"


@pytest.fixture
def _isolate_registry() -> None:
    """register_tool() mutates a module-level global shared with the real tools — restore it
    after the test so a dummy tool registered here never leaks into other test modules."""
    original = dict(registry_module._REGISTRY)
    yield
    registry_module._REGISTRY.clear()
    registry_module._REGISTRY.update(original)


def test_execution_refuses_if_preview_drifted_since_it_was_shown_to_the_analyst(
    _isolate_registry: None,
) -> None:
    """propose_actions calls preview_tool once (persisted as action.preview); approval_gate
    calls it again right before executing and must refuse to run if the two disagree — this
    is the safety net for a tool whose preview_fn could ever diverge from what it would
    actually do (block_ip can't, since it reuses the same function for both — see
    app/tools/firewall.py — but the check must hold in general). The drift must not crash the
    whole approval_gate run — it's recorded as a failed, unexecuted audit entry so any other
    approved actions in the same batch still go through."""
    calls = {"n": 0}

    def _stateful_preview(**kwargs: object) -> ToolResult:
        calls["n"] += 1
        return ToolResult(tool_name="dummy_stateful", summary=f"call {calls['n']}")

    register_tool(
        ToolSpec(
            name="dummy_stateful",
            description="A dummy active tool whose preview changes between calls.",
            risk_level="active",
            input_schema={"type": "object", "properties": {}},
            preview_fn=_stateful_preview,
        ),
        _stateful_preview,
    )
    approval_llm = RunnableLambda(
        lambda messages: ApprovalGateDecision.model_validate(
            {
                "proposed_actions": [
                    {
                        "tool_name": "dummy_stateful",
                        "args": {},
                        "justification": "j",
                        "risk_note": "r",
                    }
                ]
            }
        )
    )
    graph = _build(approval_llm)
    config = {"configurable": {"thread_id": "drift-thread"}}

    first = graph.invoke({"incident_description": "x"}, config=config)
    action_id = first["__interrupt__"][0].value["proposed_actions"][0]["id"]
    approval = ApprovalDecision(
        action_id=action_id, approved=True, decided_at=datetime.now(UTC)
    )

    resumed = graph.invoke(Command(resume=[approval.model_dump(mode="json")]), config=config)

    assert "__interrupt__" not in resumed
    entry = resumed["audit_log"][0]
    assert entry.executed is False
    assert action_id in entry.result_summary
    assert "dummy_stateful" in entry.result_summary
    assert "no longer matches" in entry.result_summary


def test_no_preview_fn_means_no_preview_but_execution_still_works(
    _isolate_registry: None,
) -> None:
    """An active tool with no preview_fn simply has preview=None — the UI falls back to
    showing args/risk_note only; execution (and the drift check, which is skipped when
    preview is None) is unaffected."""

    def _dummy_active(**kwargs: object) -> ToolResult:
        return ToolResult(tool_name="dummy_no_preview", summary="ran fine")

    register_tool(
        ToolSpec(
            name="dummy_no_preview",
            description="A dummy active tool with no preview_fn.",
            risk_level="active",
            input_schema={"type": "object", "properties": {}},
        ),
        _dummy_active,
    )
    approval_llm = RunnableLambda(
        lambda messages: ApprovalGateDecision.model_validate(
            {
                "proposed_actions": [
                    {
                        "tool_name": "dummy_no_preview",
                        "args": {},
                        "justification": "j",
                        "risk_note": "r",
                    }
                ]
            }
        )
    )
    graph = _build(approval_llm)
    config = {"configurable": {"thread_id": "no-preview-thread"}}

    first = graph.invoke({"incident_description": "x"}, config=config)
    action = first["__interrupt__"][0].value["proposed_actions"][0]
    assert action["preview"] is None

    approval = ApprovalDecision(
        action_id=action["id"], approved=True, decided_at=datetime.now(UTC)
    )
    resumed = graph.invoke(Command(resume=[approval.model_dump(mode="json")]), config=config)

    assert resumed["audit_log"][0].executed is True
    assert resumed["audit_log"][0].result_summary == "ran fine"


def test_proposal_missing_required_args_is_dropped_not_crashed() -> None:
    """Etap 9 backlog, priority 1: block_ip with args={} used to crash propose_actions with an
    uncaught TypeError (block_ip() missing 1 required positional argument: 'ip') — this is the
    exact shape all 4 known cases took (malware-keylogger, plus data-breach-s3-bucket,
    data-breach-db-exfil, insider-threat-departing-employee after the Etap 8 Part D prompt fix
    started producing args={} instead of a placeholder string). The proposal must now be dropped
    silently, same as the LLM proposing nothing — no crash, no interrupt, empty audit_log."""
    approval_llm = RunnableLambda(
        lambda messages: ApprovalGateDecision.model_validate(
            {
                "proposed_actions": [
                    {
                        "tool_name": "block_ip",
                        "args": {},
                        "justification": "j",
                        "risk_note": "r",
                    }
                ]
            }
        )
    )
    graph = _build(approval_llm)
    config = {"configurable": {"thread_id": "missing-args-thread"}}

    result = graph.invoke({"incident_description": "x"}, config=config)

    assert "__interrupt__" not in result
    assert result.get("audit_log", []) == []


def test_proposal_with_unexpected_arg_key_is_dropped_not_crashed() -> None:
    """The other TypeError flavor preview_tool's **kwargs call can hit: an unexpected keyword
    instead of a missing required one. Same required outcome — dropped, not crashed."""
    approval_llm = RunnableLambda(
        lambda messages: ApprovalGateDecision.model_validate(
            {
                "proposed_actions": [
                    {
                        "tool_name": "block_ip",
                        "args": {"ip_address": "45.83.65.12"},
                        "justification": "j",
                        "risk_note": "r",
                    }
                ]
            }
        )
    )
    graph = _build(approval_llm)
    config = {"configurable": {"thread_id": "bad-key-thread"}}

    result = graph.invoke({"incident_description": "x"}, config=config)

    assert "__interrupt__" not in result
    assert result.get("audit_log", []) == []


def test_one_malformed_proposal_does_not_block_a_good_one_in_the_same_batch() -> None:
    """The fix loops over proposals instead of a list comprehension so one bad draft can be
    skipped without losing the others — verify a valid proposal in the same decision still
    reaches the approval interrupt."""
    approval_llm = RunnableLambda(
        lambda messages: ApprovalGateDecision.model_validate(
            {
                "proposed_actions": [
                    {"tool_name": "block_ip", "args": {}, "justification": "j", "risk_note": "r"},
                    {
                        "tool_name": "block_ip",
                        "args": {"ip": "45.83.65.12"},
                        "justification": "j2",
                        "risk_note": "r2",
                    },
                ]
            }
        )
    )
    graph = _build(approval_llm)
    config = {"configurable": {"thread_id": "mixed-batch-thread"}}

    result = graph.invoke({"incident_description": "x"}, config=config)

    assert "__interrupt__" in result
    proposed = result["__interrupt__"][0].value["proposed_actions"]
    assert len(proposed) == 1
    assert proposed[0]["args"] == {"ip": "45.83.65.12"}
