from datetime import UTC, datetime

from langchain_core.messages import AIMessage
from langchain_core.runnables import RunnableLambda
from langgraph.types import Command

from app.graph.builder import build_graph
from app.graph.schemas import (
    ApprovalGateDecision,
    DiagnosticPlan,
    DiagnosticStep,
    IncidentClassification,
)
from app.main import _build_response
from app.rag.retriever import RetrievedChunk
from app.tools.approval import ApprovalDecision


class FakeRetriever:
    def search(self, query: str, top_k: int = 5) -> list[RetrievedChunk]:
        return [
            RetrievedChunk(
                text="x", source_id="cisa-ir-vr-playbooks", title="T", page=1, score=0.9
            )
        ]


def _classify_llm() -> RunnableLambda:
    return RunnableLambda(
        lambda messages: IncidentClassification(
            category="unauthorized_access",
            severity="critical",
            confidence=0.95,
            reasoning="Brute force confirmed with a successful login afterwards",
            missing_info=[],
        )
    )


def _tools_llm() -> RunnableLambda:
    return RunnableLambda(lambda messages: AIMessage(content="", tool_calls=[]))


def _plan_llm() -> RunnableLambda:
    return RunnableLambda(
        lambda messages: DiagnosticPlan(
            steps=[
                DiagnosticStep(
                    description="Review auth logs",
                    rationale="Confirm scope",
                    expected_evidence="Log entries",
                    priority=1,
                )
            ]
        )
    )


def _block_ip_proposal_llm(ip: str = "45.83.65.12") -> RunnableLambda:
    return RunnableLambda(
        lambda messages: ApprovalGateDecision.model_validate(
            {
                "proposed_actions": [
                    {
                        "tool_name": "block_ip",
                        "args": {"ip": ip},
                        "justification": "10 failed logins from this IP, then a success",
                        "risk_note": "Verify the IP isn't a shared NAT gateway",
                    }
                ]
            }
        )
    )


def _no_proposals_llm() -> RunnableLambda:
    return RunnableLambda(lambda messages: ApprovalGateDecision(proposed_actions=[]))


def _build(approval_llm: RunnableLambda) -> object:
    return build_graph(
        classify_llm=_classify_llm(),
        tools_llm=_tools_llm(),
        plan_llm=_plan_llm(),
        approval_llm=approval_llm,
        retriever=FakeRetriever(),
    )


def test_empty_proposals_do_not_interrupt() -> None:
    graph = _build(_no_proposals_llm())
    config = {"configurable": {"thread_id": "no-proposals"}}

    result = graph.invoke({"incident_description": "minor phishing click"}, config=config)

    assert "__interrupt__" not in result
    assert result.get("audit_log", []) == []


def test_proposal_interrupts_with_stable_action_id_across_resume() -> None:
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "approve-thread"}}

    first = graph.invoke({"incident_description": "brute force"}, config=config)
    assert "__interrupt__" in first
    proposed = first["__interrupt__"][0].value["proposed_actions"]
    assert len(proposed) == 1
    action_id = proposed[0]["id"]

    # get_state (a fresh read, simulating a GET after a restart) must report the exact same
    # pending action id, not one regenerated by a fresh LLM call
    snapshot = graph.get_state(config)
    assert snapshot.interrupts[0].value["proposed_actions"][0]["id"] == action_id


def test_approved_action_executes_and_is_audited() -> None:
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "approve-thread-2"}}

    first = graph.invoke({"incident_description": "brute force"}, config=config)
    action_id = first["__interrupt__"][0].value["proposed_actions"][0]["id"]

    approval = ApprovalDecision(
        action_id=action_id, approved=True, decided_at=datetime.now(UTC), comment="go ahead"
    )
    resumed = graph.invoke(Command(resume=[approval.model_dump(mode="json")]), config=config)

    assert "__interrupt__" not in resumed
    assert len(resumed["audit_log"]) == 1
    entry = resumed["audit_log"][0]
    assert entry.executed is True
    assert entry.decision.approved is True
    assert "45.83.65.12" in entry.result_summary

    response = _build_response("approve-thread-2", resumed, ())
    assert response.status == "completed"
    assert response.audit_log[0].executed is True


def test_rejected_action_is_not_executed_but_still_audited() -> None:
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "reject-thread"}}

    first = graph.invoke({"incident_description": "brute force"}, config=config)
    action_id = first["__interrupt__"][0].value["proposed_actions"][0]["id"]

    decision = ApprovalDecision(
        action_id=action_id, approved=False, decided_at=datetime.now(UTC), comment="not yet"
    )
    resumed = graph.invoke(Command(resume=[decision.model_dump(mode="json")]), config=config)

    assert "__interrupt__" not in resumed
    entry = resumed["audit_log"][0]
    assert entry.executed is False
    assert entry.decision.approved is False
    assert entry.result_summary == "Rejected by analyst; no action taken."


def test_missing_decision_defaults_to_not_approved() -> None:
    """If the client's approvals list omits an action entirely, it must still be audited
    as not-approved rather than silently dropped or (worse) executed."""
    graph = _build(_block_ip_proposal_llm())
    config = {"configurable": {"thread_id": "missing-decision-thread"}}

    graph.invoke({"incident_description": "brute force"}, config=config)
    resumed = graph.invoke(Command(resume=[]), config=config)

    assert "__interrupt__" not in resumed
    entry = resumed["audit_log"][0]
    assert entry.executed is False
    assert entry.decision.approved is False
